package model

import (
	"time"

	"github.com/lllllan02/iam/pkg/utils/stringutil"
	"github.com/speps/go-hashids"
	"gorm.io/gorm"
)

type Model struct {
	// ID is the unique in time and space value for this object. It is typically generated by
	// the storage on successful creation of a resource and is not allowed to change on PUT
	// operations.
	//
	// Populated by the system.
	// Read-only.
	ID int64 `gorm:"primarykey"`

	// InstanceID defines a string type resource identifier,
	// use prefixed to distinguish resource types, easy to remember, Url-friendly.
	InstanceID string `gorm:"unique;not null"`

	// CreatedAt, UpdatedAt, and DeletedAt represent the
	// corresponding creation, modification, and deletion times, respectively.
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt gorm.DeletedAt `gorm:"index"`
}

func NewInstanceID(prefix string, id int64) string {
	hd := hashids.NewData()
	hd.Alphabet = "abcdefghijklmnopqrstuvwxyz1234567890"
	hd.MinLength = 6
	hd.Salt = "x20k5x"

	h, err := hashids.NewWithData(hd)
	if err != nil {
		panic(err)
	}

	i, err := h.Encode([]int{int(id)})
	if err != nil {
		panic(err)
	}

	return prefix + stringutil.Reverse(i)
}
