// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/lllllan02/iam/internal/handler"
	"github.com/lllllan02/iam/internal/repository"
	"github.com/lllllan02/iam/internal/server"
	"github.com/lllllan02/iam/internal/service"
	"github.com/lllllan02/iam/pkg/app"
	"github.com/lllllan02/iam/pkg/config"
	"github.com/lllllan02/iam/pkg/log"
	"github.com/lllllan02/iam/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config, logger *log.Logger) (*app.App, func(), error) {
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(configConfig, logger)
	client := repository.NewRedis(configConfig)
	repo := repository.NewRepo(db, client, logger)
	transaction := repository.NewTransaction(repo)
	serviceService := service.NewService(logger, transaction)
	userRepo := repository.NewUserRepo(repo)
	userService := service.NewUserService(serviceService, userRepo)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	httpServer := server.NewIAMServer(configConfig, logger, userHandler)
	appApp := newApp(httpServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewIAMServer)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService)

var repoSet = wire.NewSet(repository.NewDB, repository.NewRedis, repository.NewTransaction, repository.NewRepo, repository.NewUserRepo)

func newApp(iamServer *http.Server) *app.App {
	return app.NewApp(app.WithServer(iamServer), app.WithName("iam-server"))
}
