// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/lllllan02/iam/pkg/app"
	"github.com/lllllan02/iam/pkg/config"
)

// Injectors from wire.go:

func NewWire(configConfig *config.Config) (*app.App, func(), error) {
	appApp := newApp()
	return appApp, func() {
	}, nil
}

// wire.go:

func newApp() *app.App {
	return app.NewApp(app.WithName("iam-server"))
}
